#!/bin/bash
#该脚本主要用于为教学环境的虚拟机快速配IP,网关;
#克隆的虚拟机默认有4张网卡,各自对应的可与真机通信的网段如下:
#eth0 192.168.4.0/24
#eth1 192.168.2.0/24
#eth2 201.1.1.0/24
#eth3 201.1.2.0/24

#为eth0,eth1配ip
private(){
  read -p "请输入y处的数字(1~253):" y
   if [ $y -lt 1 ]||[ $y -gt 253 ];then
      echo "数字不属于0~253范围,您需重新输入指令ipconfig"
      exit 21
    fi
  read -p "请输入网关(可不填):" gw
   if [ -z $gw ];then
      nmcli connection modify eth$n ipv4.method manual ipv4.addresses 192.168.$x.$y/24 connection.autoconnect yes &> /dev/null
      nmcli connection up eth$n &> /dev/null
      echo "您设定的网卡eth$n ip信息如下:"
      ifconfig eth$n
   else
      nmcli connection modify eth$n ipv4.method manual ipv4.addresses "192.168.$x.$y/24  $gw/24" connection.autoconnect yes
      if [ $? -ne 0 ];then
          echo "网关有误,您需重新输入指令ipconfig"
          exit 31
      fi
          nmcli connection up eth$n &> /dev/null
          echo "您设定的网卡eth$n ip信息如下:"
          ifconfig eth$n
   fi
}

#为eth2,eth3配ip
public(){
  read -p "请输入y处的数字(1~253):" y
    if [ $y -lt 1 ]||[ $y -gt 253 ];then
        echo "数字不属于0~253范围,您需重新输入指令ipconfig"
        exit 22
    fi
  read -p "请输入网关(可不填):" gw
    if [ -z $gw ];then
        nmcli connection modify eth$n ipv4.method manual ipv4.addresses 192.168.$x.$y/24 connection.autoconnect yes &> /dev/null
        nmcli connection up eth$n &> /dev/null
        echo "您设定的网卡eth$n ip信息如下:"
        ifconfig eth$n
    else
        nmcli connection modify eth$n ipv4.method manual ipv4.addresses "201.1.$x.$y/24  $gw/24" connection.autoconnect yes
        if [ $? -ne 0 ];then
            echo "网关有误,您需重新输入指令ipconfig"
            exit 32
        fi
            nmcli connection up eth$n &> /dev/null
            echo "您设定的网卡eth$n ip信息如下:"
            ifconfig eth$n
    fi
}


read -p "请输入网卡编号(0~4): eth" n
case $n in
 0)
        x=4
        echo "你将为192.168.4.y配IP"
        private;;
 1)
        x=2
        echo "你将为192.168.2.y配IP"
        private;;
 2)
        x=1
        echo "你将为201.1.1.y配IP"
        public;;
 3)
        x=2
        echo "你将为201.1.2.y配IP"
        public;;
 *)
        echo -e  "\e[31;1m该网卡编号不存在\e[0m"
        exit 10
esac

